name: CI

on: [push, pull_request]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-sanitizer-undefined:
    runs-on: ubuntu-latest
    # if: |
    #  (github.event_name == 'workflow_dispatch' ||
    #    (github.event_name == 'schedule' && github.repository == 'valkey-io/valkey') ||
    #    (github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'unstable')) &&
    #  !contains(github.event.inputs.skipjobs, 'sanitizer')
    timeout-minutes: 1440
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - name: prep
        run: |
          echo "GITHUB_REPOSITORY=${{github.event.inputs.use_repo}}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{github.event.inputs.use_git_ref}}" >> $GITHUB_ENV
          echo "skipjobs: ${{github.event.inputs.skipjobs}}"
          echo "skiptests: ${{github.event.inputs.skiptests}}"
          echo "test_args: ${{github.event.inputs.test_args}}"
          echo "cluster_test_args: ${{github.event.inputs.cluster_test_args}}"
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}
      - name: make
        run: make all-with-unit-tests OPT=-O3 SANITIZER=undefined SERVER_CFLAGS='-Werror' LUA_DEBUG=yes # we (ab)use this flow to also check Lua C API violations
      - name: testprep
        run: |
          sudo apt-get update
          sudo apt-get install tcl8.6 tclx -y
      - name: test
        if: true && !contains(github.event.inputs.skiptests, 'valkey')
        run: ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.test_args}}
      - name: module api test
        if: true && !contains(github.event.inputs.skiptests, 'modules')
        run: CFLAGS='-Werror' ./runtest-moduleapi --verbose --dump-logs ${{github.event.inputs.test_args}}
      - name: sentinel tests
        if: true && !contains(github.event.inputs.skiptests, 'sentinel')
        run: ./runtest-sentinel ${{github.event.inputs.cluster_test_args}}
      - name: cluster tests
        if: true && !contains(github.event.inputs.skiptests, 'cluster')
        run: ./runtest-cluster ${{github.event.inputs.cluster_test_args}}
      - name: unittest
        if: true && !contains(github.event.inputs.skiptests, 'unittest')
        run: ./src/valkey-unit-tests --accurate --large-memory
      - name: large memory tests
        if: true && !contains(github.event.inputs.skiptests, 'valkey') && !contains(github.event.inputs.skiptests, 'large-memory')
        run: ./runtest --accurate --verbose --dump-logs --large-memory --tags large-memory ${{github.event.inputs.test_args}}
      - name: large memory module api tests
        if: true && !contains(github.event.inputs.skiptests, 'modules') && !contains(github.event.inputs.skiptests, 'large-memory')
        run: CFLAGS='-Werror' ./runtest-moduleapi --verbose --dump-logs --large-memory --tags large-memory ${{github.event.inputs.test_args}}

  format-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: "1.22.4"

      - name: Setup YAML formatter
        run: |
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      - name: Run yamlfmt
        id: yamlfmt
        run: |
          yamlfmt -lint -conf .config/format.yml .
          # Capture the diff output
          DIFF=$(git diff)
          if [ ! -z "$DIFF" ]; then
            # Encode the diff in Base64 to ensure it's handled as a single line
            ENCODED_DIFF=$(echo "$DIFF" | base64 -w 0)
            echo "diff=$ENCODED_DIFF" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check for formatting changes
        if: ${{ steps.yamlfmt.outputs.diff }}
        run: |
          echo "ERROR: YAML file is not formatted properly. Here is the diff: "
          # Decode the Base64 diff to display it
          echo "${{ steps.clang-format.outputs.diff }}" | base64 --decode
          exit 1
        shell: bash
